# production
# 在服务器环境变量中设置

# production:
#   static_file_url_prefix: xxx
#   upload_file_base_path: xxx
#   qiniu_bucket: xxx
#   qiniu_domain: xxx
#   qiniu_base_path: xxx
#   qiniu_app_access_key: xxx
#   qiniu_app_secret_key: xxx
#   qiniu_callback_host: xxx