production:
  sessions:
    default:
      database: <%= JSON.parse(ENV["VCAP_SERVICES"])["mongodb"]["credentials"]["name"] %>
      hosts:
        - <%= JSON.parse(ENV["VCAP_SERVICES"])["mongodb"]["credentials"]["host"] %>:27017
      options:
        user: <%= JSON.parse(ENV["VCAP_SERVICES"])["mongodb"]["credentials"]["username"] %>
        password: <%= JSON.parse(ENV["VCAP_SERVICES"])["mongodb"]["credentials"]["password"] %>
