development:
  sessions:
    default:
      database: knowledge-camp-development
      hosts:
        - 127.0.0.1:27017
test:
  sessions:
    default:
      database: knowledge-camp-test
      hosts:
        - 127.0.0.1:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      hosts:
        - 10.9.58.169:27017
      database: 30e32d05-44a3-4c94-b149-bf17e2bc70e1
      username: c7cbccaf-0966-4c00-b2be-0fd99e37ece1
      password: Oj7ui-VyUNDqKKR-UMfiQA
